{% set name = "viv" %}
{% set version = "2023.1003" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viv-{{ version }}.tar.gz
  sha256: cb03f4afcabe5fead1e701d4c60d7e6a7575a4f005c0d82376057a01f8261a3e

build:
  entry_points:
    - viv = viv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8

test:
  imports:
    - viv
  commands:
    - pip check
    - viv --help
  requires:
    - pip

about:
  home: https://github.com/daylinmorgan/viv
  summary: viv isn't venv
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
