{% set name = "viv" %}
{% set version = "2024.1005" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viv-{{ version }}.tar.gz
  sha256: a0f49d7a51d2952a8d317554c0e4a7673d232a894698381ea0dfafd1ba8e19f4

build:
  entry_points:
    - viv = viv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8

test:
  imports:
    - viv
  commands:
    - pip check
    - viv --help
  requires:
    - pip

about:
  home: https://github.com/daylinmorgan/viv
  summary: viv isn't venv
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
